name = input("Enter your name:")
usn = input("enter your usn:")
course = input("Enter coure name:")
clg = inpur("Enter college Name:")
print(f"student Deatails \n 1.Name:{name}\n 2.USN:{usn}\n 3.course{course}\n 4.college:{clg}")